# App name (wird bei fly launch automatisch gesetzt)
app = "impfplan-tracker"

# Primary region (Europa - Frankfurt)
primary_region = "fra"

# Build configuration
[build]

# HTTP service configuration
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

# Health checks
[checks]
  [checks.health]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    port = 8080
    timeout = "5s"
    type = "http"

# VM configuration
[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
